### ISSUE TITLE
Parabola icon

### ISSUE THREAD

**Issue by solbjorn** [munlik/refind-theme-regular#4]
Hi there. Don't you have any plans to add an icon for Parabola GNU/Linux-libre? (https://parabola.nu)
Since I've migrated to it from Arch, I see a generic fallback Tux instead of beauty logo :unamused:
Anyway, thanks for great job!

**Comment by bobafetthotmail** [comment]
I've opened a PR that adds that icon, here https://github.com/munlik/refind-theme-regular/pull/7
